#spring:
#  application:
#    name: gateway
#
#  cloud:
#    gateway:
#      routes:
    
#      - id: ms-customer
#        uri: lb://ms-customer
#        predicates:
#        - Path=/api/ms-customer/**
#        filters: StripPrefix=2

#      - id: ms-profile
#        uri: lb://ms-profile
#        predicates:
#        - Path=/api/ms-profile/**
#        filters: StripPrefix=2
        
#
#      - id: ms-saving-account
#        uri: lb://ms-saving-account
#        predicates:
#        - Path=/api/ms-saving-account/**
#        filters: StripPrefix=2
#
#      - id: ms-fixedTerm-account
#        uri: lb://ms-fixedTerm-account
#        predicates:
#        - Path=/api/ms-fixedTerm-account/**
#        filters: StripPrefix=2

#      - id: ms-management-cta-ahorro
#        uri: lb://ms-management-cta-ahorro
#        predicates:
#        - Path=/api/ms-cta-ahorro/**
#        filters: StripPrefix=2

#server:
#  port: 8090
    
# EUREKA CLIENT    
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000